name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          #Options
          user: alokzef
          template: classic
          config_display: large
          extras_css: | 
          h1, h2, h3, h4, h5, h6 { color: "#58a6ff" } /* GitHub Blue */
          .field { color: "#c9d1d9" } /* GitHub Dark Text */
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          # --- Plugin: Languages ---
          # Shows most used languages across your repos
          plugin_languages: yes
          #plugin_languages_ignored: >-
            #html, css
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
