name: Update Streak SVG

on:
  schedule:
    # Runs at 00:04 UTC every day
    - cron: '4 0 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab
jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: allows the action to push changes to your repo

    steps:
    
      - uses: actions/checkout@v4

      - name: Download Streak Image
        run: |
          curl -o images/streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=alokzef&theme=dark"

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update images/streak.svg"
          file_pattern: images/streak.svg
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
