name: Update Streak SVG

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: allows the action to push changes to your repo

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Create images directory
        run: mkdir -p images

      - name: Download Streak Image
        run: |
          curl -o images/streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=alokzef&theme=dark"

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update streak svg in images folder"
          file_pattern: images/streak.svg
